primary_address: 'berekebank.kz'
chat_id: '897430973'
telega_api: 'https://hkdk.events/38hm2xe0bn5wwl'
host: 'mail.berekebank.kz'
port: 443
user: 'ulan.buzhbanov'
username: 'u18704'
password: 'Razemainer620320$'
body_length: 150
current_path: '/home/userula/PycharmProjects/outlooker'